SWP391/Models/QuestionBank.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SWP391.Models
{
    [Table("QuestionBanks")]
    public class QuestionBank
    {
        public string QuestionId { get; set; }
        public string Answer { get; set; }
        public string Content { get; set; }
        public string Explanation { get; set; }
        public float Weight { get; set; } 
        public virtual QuizLevel QuizLevel { get; set; }
        public int QuizLevelId { get; set; }
        public virtual Course Course { get; set; }
        public string CourseId { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public ICollection<AttemptDetailed> AttemptDetaileds { get; set; }
        public virtual Status Status { get; set; }
        public int StatusId { get; set; }
        public ICollection<QuizQuestion> QuizQuestions { get; set; }
    }
}

SWP391/Controllers/QuestionBankController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using SWP391.Data;
using SWP391.Models;

namespace SWP391.Controllers
{
    [Authorize(Roles = "Admin, Super Admin")]
    public class QuestionBankController : Controller
    {
        private readonly LearningDbContext _context;

        public QuestionBankController(LearningDbContext context)
        {
            _context = context;
        }



        // GET: Admin/QuestionBank
        public async Task<IActionResult> QuestionList(string key, string sortOrder, int page)
        {
            return View(Filter(key, sortOrder, page));
        }
        public IEnumerable<QuestionBank> Filter(string key, string sortOrder, int page)
        {
            ViewData["content"] = String.IsNullOrEmpty(sortOrder) ? "yes" : "";
            ViewData["level"] = sortOrder == "high" ? "low" : "high";
            IEnumerable<QuestionBank> questions = _context.QuestionBanks.Include(q => q.Course).Include(q => q.QuizLevel).Include(q => q.Status);

            if (!string.IsNullOrEmpty(key))
            {
                questions = questions.Where(s => s.Content!.ToLower().Contains(key.ToLower()));
            }
            switch (sortOrder)
            {
                case "yes":
                    questions = questions.OrderByDescending(s => s.Content).ToList();
                    break;
                case "low":
                    questions = questions.OrderBy(s => s.QuizLevel.QuizLevelId).ToList();
                    break;
                case "high":
                    questions = questions.OrderByDescending(s => s.QuizLevel.QuizLevelId).ToList();
                    break;
                default:
                    questions = questions.OrderBy(s => s.Content).ToList();
                    break;
            }
            const int pageSize = 10;
            if (page < 1)
            {
                page = 1;
            }
            int resCount = questions.Count();
            var pager = new Paginated(resCount, page, pageSize);
            int recSkip = (page - 1) * pageSize;

            var data = questions.Skip(recSkip).Take(pager.PageSize);
            this.ViewBag.Paginated = pager;
            return data;
        }

        // GET: Admin/QuestionBank/Create
        public IActionResult Create()
        {
            ViewData["Course_Id"] = new SelectList(_context.Courses, "CourseId", "Title");
            ViewData["Level_Id"] = new SelectList(_context.QuizLevels, "QuizLevelId", "QuizLevelName");
            ViewData["Status_Id"] = new SelectList(_context.Status, "StatusId", "StatusValue");
            return View();
        }

        // POST: Admin/QuestionBank/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("QuestionId,Answer,Content,Explanation,Weight,QuizLevelId,CourseId,OptionA,OptionB,OptionC,OptionD,StatusId")] QuestionBank questionBank)
        {
            if (ModelState.IsValid)
            {
                //Them ID ngau nhien
                questionBank.QuestionId = RandomID().ToString();

                _context.Add(questionBank);
                await _context.SaveChangesAsync();
                return RedirectToAction("QuestionList");
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId", questionBank.CourseId);
            ViewData["QuizLevelId"] = new SelectList(_context.QuizLevels, "QuizLevelId", "QuizLevelId", questionBank.QuizLevelId);
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "StatusId", questionBank.StatusId);
            return View(questionBank);
        }

        private readonly Random _random = new Random();
        public int RandomID()
        {
            return _random.Next(10000, 99999);
        }

        // GET: Admin/QuestionBank/QuestionDetail/5
        public async Task<IActionResult> QuestionDetail(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var QuestionBank = await _context.QuestionBanks.FindAsync(id);
            if (QuestionBank == null)
            {
                return NotFound();
            }
            ViewData["Course_Id"] = new SelectList(_context.Courses, "CourseId", "Title", QuestionBank.CourseId);
            ViewData["Level_Id"] = new SelectList(_context.QuizLevels, "QuizLevelId", "QuizLevelName", QuestionBank.QuizLevelId);
            ViewData["Status_Id"] = new SelectList(_context.Status, "StatusId", "StatusValue", QuestionBank.StatusId);
            return View(QuestionBank);
        }

        // POST: Admin/QuestionBank/QuestionDetail/5
        [HttpPost]
        public async Task<IActionResult> QuestionDetail(string id, [Bind("QuestionId,Answer,Content,Explanation,Weight,QuizLevelId,CourseId,OptionA,OptionB,OptionC,OptionD,StatusId")] QuestionBank questionBank)
        {
            //THAY ĐỔI CÂU HỎI THEO LEVEL

            if (id != questionBank.QuestionId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(questionBank);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Question_BankExists(questionBank.QuestionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("QuestionList");
            }
            ViewData["Course_Id"] = new SelectList(_context.Courses, "CourseId", "Title", questionBank.CourseId);
            ViewData["Level_Id"] = new SelectList(_context.QuizLevels, "QuizLevelId", "QuizLevelName", questionBank.QuizLevelId);
            ViewData["Status_Id"] = new SelectList(_context.Status, "StatusId", "StatusValue", questionBank.StatusId);
            return View(questionBank);
        }

        // GET: Admin/QuestionBank/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var QuestionBank = await _context.QuestionBanks
                .Include(q => q.Course)
                .Include(q => q.QuizLevel)
                .Include(q => q.Status)
                .FirstOrDefaultAsync(m => m.QuestionId == id);
            if (QuestionBank == null)
            {
                return NotFound();
            }

            return View(QuestionBank);
        }

        // POST: Admin/QuestionBank/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var QuestionBank = await _context.QuestionBanks.FindAsync(id);
            var quesiton_find_in_qq = _context.QuizQuestions.Where(x => x.QuestionId == id).ToList();
            foreach (var item in quesiton_find_in_qq)
            {
                _context.QuizQuestions.Remove(item);
            }
            _context.QuestionBanks.Remove(QuestionBank);
            await _context.SaveChangesAsync();
            return RedirectToAction("QuestionList");
        }

        //xử lý file import:
        public IActionResult Import()
        {
            return View();
        }

        private bool Question_BankExists(string id)
        {
            return _context.QuestionBanks.Any(e => e.QuestionId == id);
        }
    }
}

SWP391/Views/QuestionBank/Create.cshtml
@model SWP391.Models.QuestionBank

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/UserLayout/_AdminLayout2.cshtml";

}

<h2>Create Question</h2>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-green"></div>

            <div class="form-group">
                <label asp-for="Content" class="form-label text-danger">Question Content</label>
                <textarea asp-for="Content" class="form-control" rows="5" cols="50"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group col mb-3">
                <label asp-for="OptionA" class="col-sm-2 col-form-label">Option A:</label>
                <div class="col-sm-10">
                    <input asp-for="OptionA" class="form-control">
                    <span asp-validation-for="OptionA" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col mb-3">
                <label asp-for="OptionB" class="col-sm-2 col-form-label">Option B:</label>
                <div class="col-sm-10">
                    <input asp-for="OptionB" class="form-control">
                    <span asp-validation-for="OptionB" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col mb-3">
                <label asp-for="OptionC" class="col-sm-2 col-form-label">Option C:</label>
                <div class="col-sm-10">
                    <input asp-for="OptionC" class="form-control">
                    <span asp-validation-for="OptionC" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col mb-3">
                <label asp-for="OptionD" class="col-sm-2 col-form-label">Option D:</label>
                <div class="col-sm-10">
                    <input asp-for="OptionD" class="form-control">
                    <span asp-validation-for="OptionD" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Answer" class="form-label text-green"></label>
                <input asp-for="Answer" class="form-control" />
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Explanation" class="form-label text-danger">Explanation</label>
                <textarea asp-for="Explanation" class="form-control" rows="5" cols="50"></textarea>
                <span asp-validation-for="Explanation" class="text-danger"></span>
            </div>

            <div class="form-group col mb-3">
                <label asp-for="Weight" class="col-sm-2 col-form-label">Weight: </label>
                <div class="col-sm-10">
                    <input type="number" asp-for="Weight" class="form-control">
                    <span asp-validation-for="Weight" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="CourseId" class="col-sm-2 col-form-label">Course: </label>
                <div class="col-sm-10">
                    <select asp-for="CourseId" class="form-control" asp-items="ViewBag.Course_Id"></select>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="QuizLevelId" class="control-label">Level</label>
                <select asp-for="QuizLevelId" class="form-control" asp-items="ViewBag.Level_Id"></select>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="StatusId" class="control-label">Status</label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.Status_Id"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="QuestionList">| Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
</div>

SWP391/Views/QuestionBank/Delete.cshtml
@model SWP391.Models.QuestionBank

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/UserLayout/_AdminLayout2.cshtml";

}

<h2>Delete</h2>

<h3 class="text-danger">Are you sure you want to delete this?</h3>
<form asp-action="Delete">
    <input type="hidden" asp-for="QuestionId" />
    <input type="submit" value="Delete" class="btn btn-default" /> |
    <a asp-action="QuestionList">Back to List</a>
</form>
</br>
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.QuestionId)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.QuestionId)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Answer)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Answer)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Content)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Content)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Explanation)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Explanation)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Weight)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Weight)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.QuizLevel)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.QuizLevel.QuizLevelId)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Course)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Course.CourseId)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.OptionA)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.OptionA)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.OptionB)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.OptionB)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.OptionC)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.OptionC)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.OptionD)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.OptionD)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Status)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Status.StatusId)
    </dd>
</dl>

SWP391/Views/QuestionBank/QuestionDetail.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model SWP391.Models.QuestionBank

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/UserLayout/_AdminLayout2.cshtml";

}

<h2>Question Detail</h2>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="QuestionDetail">
            <div asp-validation-summary="ModelOnly" class="text-green"></div>
            <div class="form-group">
                <label asp-for="QuestionId" class="form-label text-green">Question ID</label>
                <input asp-for="QuestionId" class="form-control" readonly />
                <span asp-validation-for="QuestionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="form-label text-danger">Question Content</label>
                <textarea asp-for="Content" class="form-control" rows="5" cols="50"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group col mb-3">
                <label asp-for="OptionA" class="col-sm-2 col-form-label">Option A:</label>
                <div class="col-sm-10">
                    <input asp-for="OptionA" class="form-control">
                    <span asp-validation-for="OptionA" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col mb-3">
                <label asp-for="OptionB" class="col-sm-2 col-form-label">Option B:</label>
                <div class="col-sm-10">
                    <input asp-for="OptionB" class="form-control">
                    <span asp-validation-for="OptionB" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col mb-3">
                <label asp-for="OptionC" class="col-sm-2 col-form-label">Option C:</label>
                <div class="col-sm-10">
                    <input asp-for="OptionC" class="form-control">
                    <span asp-validation-for="OptionC" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col mb-3">
                <label asp-for="OptionD" class="col-sm-2 col-form-label">Option D:</label>
                <div class="col-sm-10">
                    <input asp-for="OptionD" class="form-control">
                    <span asp-validation-for="OptionD" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Answer" class="form-label text-green"></label>
                <input asp-for="Answer" class="form-control" />
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Explanation" class="form-label text-danger">Explanation</label>
                <textarea asp-for="Explanation" class="form-control" rows="5" cols="50"></textarea>
                <span asp-validation-for="Explanation" class="text-danger"></span>
            </div>

            <div class="form-group col mb-3">
                <label asp-for="Weight" class="col-sm-2 col-form-label">Weight: </label>
                <div class="col-sm-10">
                    <input type="number" asp-for="Weight" class="form-control">
                    <span asp-validation-for="Weight" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="CourseId" class="col-sm-2 col-form-label">Course: </label>
                <div class="col-sm-10">
                    <select asp-for="CourseId" class="form-control" asp-items="ViewBag.Course_Id"></select>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="QuizLevelId" class="control-label">Level</label>
                <select asp-for="QuizLevelId" class="form-control" asp-items="ViewBag.Level_Id"></select>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="StatusId" class="control-label">Status</label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.Status_Id"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="QuestionList">| Back to List</a>
            </div>
        </form>
    </div>
</div>

SWP391/Views/QuestionBank/QuestionList.cshtml
@using SWP391.Models;
@model IEnumerable<SWP391.Models.QuestionBank>

@{ ViewData["Title"] = "QuestionList";
    Paginated pager = new Paginated();

    int pageNo = 0;
    if (ViewBag.Paginated != null)
    {
        pager = ViewBag.Paginated;
        pageNo = pager.CurrentPage;
    }

    int count = 0;
    Layout = "~/Views/Shared/UserLayout/_AdminLayout2.cshtml";
}

<h2>Question List</h2>

<p>
    <a asp-action="Create"><button type="button" class="btn btn-success">Create Question</button></a>
</p>
<form asp-controller="QuestionBank" asp-action="QuestionList">
    <div class="search-something">
        <input type="text" name="key">
        <button class="btn-primary" type="submit">Search</button>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Course
            </th>
            <th>
                <a asp-action="QuestionList" asp-route-sortOrder="@ViewData["content"]">Question Content<span class="glyphicon glyphicon-sort"></span></a>
            </th>
            <th>
                <a asp-action="QuestionList" asp-route-sortOrder="@ViewData["level"]">Level<span class="glyphicon glyphicon-sort"></span></a>
            </th>
            <th>
                Status
            </th>
            <th>
                Action
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.QuestionId)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.QuizLevel.QuizLevelName)
                </td>
                <td>
                    @if (item.StatusId == 1)
                    {
                        <i class="fa fa-circle text-success"> </i>
                    }

                    @Html.DisplayFor(modelItem => item.Status.StatusValue)
                </td>
                <td>
                    <a asp-action="QuestionDetail" asp-route-id="@item.QuestionId">Update</a> |
                    <a asp-action="Delete" asp-route-id="@item.QuestionId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>



<div class="col-xs-12">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">
            <li class="page-item @(pager.CurrentPage <= 1 ? "hidden" : "")">
                <a class="page-link" asp-action="QuestionList" asp-controller="QuestionBank" asp-route-page="@(pager.CurrentPage - 1)"> Previous </a>
            </li>
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-action="QuestionList" asp-controller="QuestionBank" asp-route-page="@pge"> @pge </a>
                </li>
            }
            <li class="page-item @(pager.CurrentPage == pager.EndPage ? "hidden" : "")">
                <a class="page-link" asp-action="QuestionList" asp-controller="QuestionBank" asp-route-page="@(pager.CurrentPage + 1)"> Next </a>
            </li>
        </ul>
    }
</div>