SWP391/Controllers/UserCourseController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SWP391.Data;
using SWP391.Models;
using SWP391.Utility.BraintreeService;
using SWP391.Views.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SWP391.Controllers
{
    public class UserCourseController : Controller
    {
        private readonly LearningDbContext _db;
        private readonly IWebHostEnvironment WebHostEnvironment;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly IBraintreeService _braintreeService;
        public UserCourseController(IBraintreeService braintreeService, LearningDbContext db, IWebHostEnvironment webHostEnvironment, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _db = db;
            WebHostEnvironment = webHostEnvironment;
            _userManager = userManager;
            _signInManager = signInManager;
            _braintreeService = braintreeService;
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(string id)
        {
            var course = _db.Courses.Find(id);
            _db.Courses.Remove(course);
            _db.SaveChanges();
            return RedirectToAction("course", "user");
        }

        public IActionResult CreateTopic(int i)
        {
            NewCourseVM nc = new NewCourseVM();
            Topic t = new Topic();
            return PartialView("CreateTopic", t);
        }

        public IActionResult EditCourse(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            NewCourseVM newCourseVM = new NewCourseVM()
            {
                Course = new Course(),
                TypeDropDown = _db.Categories.Select(i => new SelectListItem
                {
                    Text = i.CategoryValue,
                    Value = i.CategoryId.ToString()
                })

            };
            Course c = _db.Courses.Find(id);
            newCourseVM.Course = c;
            if (newCourseVM.Course == null)
            {
                return NotFound();
            }
            newCourseVM.Course.Category = _db.Categories.Find(newCourseVM.Course.CategoryId);
            return View(newCourseVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCourse(NewCourseVM c)
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (ModelState.IsValid)
            {
                if (c.Course.ImgFile != null)
                {
                    string wwwroot = WebHostEnvironment.WebRootPath;
                    string filename = Path.GetFileNameWithoutExtension(c.Course.ImgFile.FileName);
                    string ex = Path.GetExtension(c.Course.ImgFile.FileName);
                    c.Course.ThumbnailURL = filename = filename + ex;
                    string path = Path.Combine(wwwroot + "/img/", filename);
                    using (var filestream = new FileStream(path, FileMode.Create))
                    {
                        await c.Course.ImgFile.CopyToAsync(filestream);
                    }
                }
                
                c.Course.UserId = user.Id;
                c.Course.SlideId = 1;
                c.Course.StatusId = 1;
                _db.Update(c.Course);
                _db.SaveChanges();
                return RedirectToAction("course", "user");
            }
            return View(c);
        }
    }
}

SWP391/Views/UserCourse/CreateTopic.cshtml
@model Topic
<div class="col-12 list-topic">
    <span>Topic</span>
    <div class="form-group topic-item">
        <label asp-for="@Model.TopicId" class="col-form-label"></label>
        <div>
            <input class="form-control topic-item" asp-for="@Model.TopicId">
        </div>
    </div>
    <div class="form-group topic-item">
        <label asp-for="@Model.TopicOrder" class="col-form-label"></label>
        <div>
            <input class="form-control" asp-for="@Model.TopicOrder" min="1">
        </div>
    </div>
    <div class="form-group topic-item">
        <label asp-for="@Model.TopicName" class="col-form-label"></label>
        <div>
            <input class="form-control" asp-for="@Model.TopicName">
        </div>
    </div>
    <div class="form-group topic-item">
        <button type="button" class="addService btn btn-delete deleteService">Delete</button>
    </div>
</div>

SWP391/Views/UserCourse/EditCourse.cshtml
@model SWP391.Views.ViewModel.NewCourseVM
@{
    //ViewData["Title"] = "Admin Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="ttr-wrapper">
    <div class="container-fluid">
        @*<div class="db-breadcrumb">
                <h4 class="breadcrumb-title">Add listing</h4>
                <ul class="db-breadcrumb-list">
                    <li><a href="#"><i class="fa fa-home"></i>Home</a></li>
                    <li>Add listing</li>
                </ul>
            </div>*@
        <div class="row">
            <!-- Your Profile Views Chart -->
            <div class="col-lg-12 m-b30">
                <div class="widget-box">
                    <div class="wc-title" style="padding-left: 30px">
                        <h4>Add listing</h4>
                    </div>
                    <div class="widget-inner">
                        <form class="edit-profile m-b30" method="post" asp-action="EditCourse" asp-controller="UserCourse" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3>1. Basic info</h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label asp-for="@Model.Course.CourseId" class="col-form-label"></label>
                                    <div>
                                        <input class="form-control" asp-for="@Model.Course.CourseId">
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label asp-for="@Model.Course.Title" class="col-form-label"></label>
                                    <div>
                                        <input class="form-control" asp-for="@Model.Course.Title">
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label asp-for="@Model.Course.Description" class="col-form-label"></label>
                                    <div>
                                        <input class="form-control" asp-for="@Model.Course.Description">
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label asp-for="@Model.Course.ImgFile" class="col-form-label"></label>
                                    <div>
                                        <input class="form-control" asp-for="@Model.Course.ImgFile">
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label asp-for="@Model.Course.CreatedDate" class="col-form-label"></label>
                                    <div>
                                        <input class="form-control" asp-for="@Model.Course.CreatedDate">
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label asp-for="@Model.Course.Price" class="col-form-label"></label>
                                    <div>
                                        <input class="form-control" asp-for="@Model.Course.Price">
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <select asp-for="@Model.Course.CategoryId" asp-items="@Model.TypeDropDown" class="form-control">
                                        <option selected>--Select Categories--</option>
                                    </select>
                                    <span asp-validation-for="@Model.Course.CategoryId" class="text-danger"></span>
                                </div>
                                <div class="form-group col-6">
                                    <label asp-for="@Model.Course.ThumbnailURL" class="col-form-label"></label>
                                    <div>
                                        <input class="form-control" asp-for="@Model.Course.ThumbnailURL" hidden>
                                    </div>
                                    <img src="~/CourseImg/@Model.Course.ThumbnailURL" />
                                </div>
                                <div class="seperator"></div>

                                @*<div class="col-12">
            <div class="ml-auto">
                <h3>2. Topic info</h3>
            </div>
        </div>*@
                                @*<div class="col-12">
        <button type="button" data-url="@Url.Action("CreateTopic","UserCourse")" class="addService btn">Add Topic</button>
        </div>
        <div id="Topic" class="row">
            <div class="col-12 list-topic">
                <span>Topic</span>
                <div class="form-group topic-item">
                    <label asp-for="@Model.Topic.TopicId" class="col-form-label"></label>
                    <div>
                        <input class="form-control topic-item" asp-for="@Model.Topic.TopicId">
                    </div>
                </div>
                <div class="form-group topic-item">
                    <label asp-for="@Model.Topic.TopicOrder" class="col-form-label"></label>
                    <div>
                        <input class="form-control" asp-for="@Model.Topic.TopicOrder" min="1">
                    </div>
                </div>
                <div class="form-group topic-item">
                    <label asp-for="@Model.Topic.TopicName" class="col-form-label"></label>
                    <div>
                        <input class="form-control" asp-for="@Model.Topic.TopicName">
                    </div>
                </div>
                <div class="form-group topic-item">
                    <button type="button" class="addService btn btn-delete deleteService">Delete</button>
                </div>
            </div>

        </div>*@

                                <div class="col-12">

                                    <input type="submit" class="btn btn-delete" value="Save changes" />
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Your Profile Views Chart END-->
        </div>
    </div>
</main>
<script src="/assets/js/jquery.min.js"></script>
@*<script type="text/javascript">
        var topicId = '1';
        var order = '2';
        var name1 = '3';
        var html = '<div class="col-12 list-topic"><span>Topic</span><div class="form-group topic-item"><label asp-for="' + topicId + '" class="col-form-label"></label><div><input class="form-control topic-item" asp-for="' + topicId + '"></div></div><div class="form-group topic-item"><label asp-for="' + order + '" class="col-form-label"></label><div><input class="form-control" asp-for="' + order + '"></div></div><div class="form-group topic-item"><label asp-for="' + name1 + '" class="col-form-label"></label><div><input class="form-control" asp-for="' + name1 + '"></div></div></div>';

        $(document).on('click', '.addService', function () {
            $(this).parent().append(html);
        });
    </script>*@
<script type="text/javascript">
    $('.addService').on('click', function (e) {
        e.preventDefault();
        e.stopPropagation();
        var $topic = $('#Topic'),
            url = $(this).data('url');
        $.get(url, function (data) {
            $topic.append(data);
            
        });
    });
    
</script>